Models/AddMovieVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace PhotoUpload.Models
{
public class AddMovieVM
{
    [DisplayName("Title: ")]
    public string Title { get; set; }

    [DisplayName("Release Date: ")]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime ReleaseDate { get; set; }

    [DisplayName("Running Time (Minutes):")]
    
    public int RunningTimeMinutes { get; set; }
    
    public List<CheckBoxListItem> Genres { get; set; }

    public AddMovieVM()
    {
        Genres = new List<CheckBoxListItem>();
    }
}
}

Models/CheckListItem.cs
public class CheckBoxListItem
{
    public int ID { get; set; }
    public string Display { get; set; }
    public bool IsChecked { get; set; }
}

Models/ErrorViewModel.cs
using System;

namespace PhotoUpload.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
using System.Collections.Generic;
namespace PhotoUpload.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
          public string Image{get;set;}
        
    }
}

Models/StudentImage.cs
using PhotoUpload.Models;
namespace PhotoUpload.Models
{
    public class StudentImage
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public Student Student {get;set;}
        public int StudentId { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhotoUpload.Models;

namespace PhotoUpload.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using System;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PhotoUpload.Models;
using System.Collections.Generic;
using PhotoUpload.Data;


namespace PhotoUpload.Controllers
{
    public class MovieController : Controller
    {

        private readonly ApplicationDbContext _context;
        public MovieController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            AddMovieVM model = new AddMovieVM();
            var allGenres = GenreManager.GetAll(); //returns List<Genre>
            var checkBoxListItems = new List<CheckBoxListItem>();
            foreach (var genre in allGenres)
            {
                checkBoxListItems.Add(new CheckBoxListItem()
                {
                    ID = genre.ID,
                    Display = genre.Name,
                    IsChecked = false //On the add view, no genres are selected by default
                });
            }
            model.Genres = checkBoxListItems;
            return View(model);
        }
    }
}

Controllers/PhotoController.cs
using System;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PhotoUpload.Models;
using System.Collections.Generic;


using PhotoUpload.Data;


namespace PhotoUpload.Controllers
{
    public class PhotoController : Controller
    {

        private readonly ApplicationDbContext _context;
        public PhotoController(ApplicationDbContext context)
        {
            _context = context;
        }
      
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upload()
        {
            return View();
        }
         public IActionResult UploadFiles()
        {
            return View();
        }
        [HttpPost("FileUpload")]
         public async Task<IActionResult> NewStudent(Student p)
        {
            var files = HttpContext.Request.Form.Files;
            foreach (var Image in files)
            {
                if (Image != null && Image.Length > 0)
                {
                    var file = Image;
                    var uploads = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/studentimages");
                    if (file.Length > 0)
                    {
                        var fileName = ContentDispositionHeaderValue.Parse
                            (file.ContentDisposition).FileName.Trim('"');

                        System.Console.WriteLine(fileName);
                        using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                              
                        p.Image = p.Image +"-"+ file.FileName;
                         }
                   }
                }
            }
             _context.Students.Add(p);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    // process uploaded files
    // Don't rely on or trust the FileName property without validation. }
            public IActionResult All()
            {
                return View(_context.Students.ToList());
            }
              public IActionResult Details(int id)
            {
                
                
                 var data = _context.Students.FirstOrDefault(x=>x.Id==id);
                 string[] filenames = data.Image.Split('-');
                                   return View(data);

            }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Photo/All.cshtml
@model List<Student>

    @foreach (var item in Model)
    {
        @item.Name
        @item.Address
        <a asp-action="Details" asp-controller="Photo" asp-route-id="@item.Id">View </a>
    }

Views/Photo/Details.cshtml
@model Student


<h1> hello @Model.Name </h1>

@foreach (var x in ViewBag.image)
{
        
        
         <img src="/studentimages/@x" height="100px" width="100px">
          <br>
}

Views/Photo/Upload.cshtml
@model Student
<form method="post" enctype="multipart/form-data" asp-controller="Photo" asp-action="NewStudent">
<div class="form-group">
    <input type="hidden" asp-for="Id">
    <div class="col-md-10">
        <p>Upload one or more files using this form:</p>
        <input type="file" name="files" multiple />
    </div>
</div>
<div class="form-group">
    <div class="col-md-10">
        <input type="text" asp-for="Name" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-10">
        <input type="text" asp-for="Address" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-10">
        <input type="submit" value="Upload" />
    </div>
</div>
</form>

Views/Shared/AddMovieVm.cshtml
@model AddMovieVM
...
@using (Html.BeginForm())
{
    <div>
        <div>
            @Html.LabelFor(x => x.Title)
            @Html.TextBoxFor(x => x.Title)
        </div>
        <div>
            @Html.LabelFor(x => x.ReleaseDate)
            @Html.EditorFor(x => x.ReleaseDate)
        </div>
        <div>
            @Html.LabelFor(x => x.RunningTimeMinutes)
            @Html.TextBoxFor(x => x.RunningTimeMinutes)
        </div>
        <div>
            @Html.EditorFor(x => x.Genres)
        </div>
        <input type="submit" value="Go!" />
    </div>
}

Views/Shared/CheckBoxListItem.cshtml
@model CheckBoxListItem

@Html.HiddenFor(x => x.ID)
@Html.CheckBoxFor(x => x.IsChecked)
@Html.LabelFor(x => x.IsChecked, Model.Display)
<br />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhotoUpload</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhotoUpload</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PhotoUpload - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>